apiVersion: apps/v1
kind: Deployment
metadata:
  name: assinatura
  namespace: assinatura
  labels:
    app: assinatura
spec:
  replicas: 2
  selector:
    matchLabels:
      app: assinatura
  template:
    metadata:
      labels:
        app: assinatura
        monitoramento-prometheus: "enabled"
    spec:
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
        - name: assinatura-container
          image: harbor.grupoagp.com.br/k8s/assinatura:d302e57
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: assinatura
  namespace: assinatura
  labels:
    app: assinatura
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: assinatura
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: assinatura
  namespace: assinatura
  labels:
    app: assinatura
  # Removi a annotation de rewrite para evitar quebra de CSS/JS
spec:
  ingressClassName: nginx
  rules:
    - host: "assinatura.k8s.local"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: assinatura
                port:
                  number: 80