apiVersion: apps/v1
kind: Deployment
metadata:
  name: assinatura
  namespace: assinatura
  labels:
    app: assinatura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assinatura
  template:
    metadata:
      labels:
        app: assinatura
        monitoramento-prometheus: "enabled"
    spec:
      containers:
        - name: assinatura-container
<<<<<<< HEAD
          image: harbor.grupoagp.com.br/k8s/assinatura:f3cc3cd
=======
          image: harbor.grupoagp.com.br/k8s/assinatura:f3cc3cd
>>>>>>> 33104e28bb345b77fc90848d8e8d8797d20781d2
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
        - name: nginx-exporter
          image: harbor.grupoagp.com.br/k8s/assinatura:f3cc3cd
          args:
            - -nginx.scrape-uri=http://localhost:80/stub_status
          ports:
            - containerPort: 9113
              name: metrics
---

apiVersion: v1
kind: Service
metadata:
  name: assinatura
  namespace: assinatura
  labels:
    app: assinatura
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: assinatura

---
# --- 3. Ingress ---
# O Ingress gere o acesso externo à sua aplicação.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: assinatura-ingress
   namespace: assinatura
  labels:
    app: assinatura
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: "assinatura.k8s.local" # O domínio para aceder à aplicação
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: assinatura # Aponta para o Service correto
                port:
                  number: 80


